// <auto-generated />
using System;
using CentimeterX.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CentimeterX.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentimeterX.API.Models.EstacaoBase", b =>
                {
                    b.Property<int>("IdEstacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstacao"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CD_CODIGO");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_ESTACAO");

                    b.Property<bool>("Online")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_ONLINE");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ULTIMA_ATUALIZACAO");

                    b.HasKey("IdEstacao");

                    b.ToTable("CX_ESTACAO_BASE");
                });

            modelBuilder.Entity("CentimeterX.API.Models.Ocorrencia", b =>
                {
                    b.Property<int>("IdOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OCORRENCIA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOcorrencia"));

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIADA_EM");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DS_FOTO_URL");

                    b.Property<int>("IdRover")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ROVER");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_LONGITUDE");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_OCORRENCIA");

                    b.HasKey("IdOcorrencia");

                    b.HasIndex("IdRover");

                    b.ToTable("CX_OCORRENCIA");
                });

            modelBuilder.Entity("CentimeterX.API.Models.Rover", b =>
                {
                    b.Property<int>("IdRover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ROVER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRover"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<int>("IdEstacaoBase")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTACAO_BASE");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_ROVER");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_STATUS");

                    b.Property<string>("TIPO_ROVER")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("IdRover");

                    b.HasIndex("IdEstacaoBase");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CX_ROVER");

                    b.HasDiscriminator<string>("TIPO_ROVER").HasValue("Rover");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CentimeterX.API.Models.SessaoCorrecao", b =>
                {
                    b.Property<int>("IdSessao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SESSAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSessao"));

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ENCERRADO_EM");

                    b.Property<int>("IdEstacaoBase")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTACAO_BASE");

                    b.Property<int>("IdRover")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ROVER");

                    b.Property<DateTime>("IniciouEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INICIOU_EM");

                    b.Property<double>("PrecisaoHorizontalCm")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_PRECISAO_HORIZONTAL_CM");

                    b.Property<double>("PrecisaoVerticalCm")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_PRECISAO_VERTICAL_CM");

                    b.Property<string>("SistemaSatelite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_SISTEMA_SATELITE");

                    b.Property<int>("StatusFix")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_STATUS_FIX");

                    b.HasKey("IdSessao");

                    b.HasIndex("IdEstacaoBase");

                    b.HasIndex("IdRover");

                    b.ToTable("CX_SESSAO_CORRECAO");
                });

            modelBuilder.Entity("CentimeterX.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<int>("Perfil")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_PERFIL");

                    b.HasKey("IdUsuario");

                    b.ToTable("CX_USUARIO");
                });

            modelBuilder.Entity("CentimeterX.API.Models.Drone", b =>
                {
                    b.HasBaseType("CentimeterX.API.Models.Rover");

                    b.Property<double>("AltitudeMaxima")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_ALTITUDE_MAXIMA");

                    b.Property<int>("AutonomiaVoo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_AUTONOMIA_VOO");

                    b.ToTable("CX_ROVER");

                    b.HasDiscriminator().HasValue("DRONE");
                });

            modelBuilder.Entity("CentimeterX.API.Models.MaquinaAgricola", b =>
                {
                    b.HasBaseType("CentimeterX.API.Models.Rover");

                    b.Property<decimal>("LarguraImplemento")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("NR_LARGURA_IMPLEMENTO");

                    b.Property<string>("ModeloTrator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_MODELO_TRATOR");

                    b.ToTable("CX_ROVER");

                    b.HasDiscriminator().HasValue("MAQUINA_AGRICOLA");
                });

            modelBuilder.Entity("CentimeterX.API.Models.VeiculoAutonomo", b =>
                {
                    b.HasBaseType("CentimeterX.API.Models.Rover");

                    b.Property<int>("NivelAutonomia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_NIVEL_AUTONOMIA");

                    b.Property<double>("VelocidadeMaxima")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NR_VELOCIDADE_MAXIMA");

                    b.ToTable("CX_ROVER");

                    b.HasDiscriminator().HasValue("VEICULO_AUTONOMO");
                });

            modelBuilder.Entity("CentimeterX.API.Models.Ocorrencia", b =>
                {
                    b.HasOne("CentimeterX.API.Models.Rover", "Rover")
                        .WithMany()
                        .HasForeignKey("IdRover")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rover");
                });

            modelBuilder.Entity("CentimeterX.API.Models.Rover", b =>
                {
                    b.HasOne("CentimeterX.API.Models.EstacaoBase", "EstacaoBase")
                        .WithMany()
                        .HasForeignKey("IdEstacaoBase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentimeterX.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstacaoBase");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentimeterX.API.Models.SessaoCorrecao", b =>
                {
                    b.HasOne("CentimeterX.API.Models.EstacaoBase", "EstacaoBase")
                        .WithMany()
                        .HasForeignKey("IdEstacaoBase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentimeterX.API.Models.Rover", "Rover")
                        .WithMany()
                        .HasForeignKey("IdRover")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstacaoBase");

                    b.Navigation("Rover");
                });
#pragma warning restore 612, 618
        }
    }
}
